# Generated by Django 4.2.1 on 2023-06-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_prompt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaimodel',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
