# Generated by Django 4.2.1 on 2023-06-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openai_prompt', '0002_openaimodel_conversation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=15, null=True)),
                ('content', models.CharField(blank=True, max_length=15, null=True)),
                ('conversation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openai_prompt.openaimodel')),
            ],
        ),
    ]
